### ISSUE TITLE
Multiple packages on npm

### ISSUE THREAD

**Issue by levaitamas** [l7mp/l7mp#89]
I have found these 2 packages on [npm website](https://www.npmjs.com/search?q=l7mp):
* [l7mp](https://www.npmjs.com/package/l7mp): this one is mentioned in the README, but it is outdated (v0.5.2)
* [@l7mp/l7mp](https://www.npmjs.com/package/@l7mp/l7mp): this quirky named one seems current (v0.5.4)

I am looking for the latest and greatest. Which one shall I pick?

**Comment by VidarHUN** [comment]
There was a mistake and the oldest has not been removed yet. 
Please use this one:  [@l7mp/7mp](https://www.npmjs.com/package/@l7mp/l7mp)

**Comment by levaitamas** [comment]
Awesome! Thank you for your quick reply @VidarHUN!

**Comment by rg0now** [comment]
The old version should be removed now from npmjs, closing this issue. Thanks for reporting!
