### ISSUE TITLE
Missing monitoring.js after npm install

### ISSUE THREAD

**Issue by levaitamas** [l7mp/l7mp#97]
I made an install with the `npm i @l7mp/l7mp` command. 

As I was starting l7mp, I have received an error message that monitoring can not be loaded.

```sh
$ cd node_modules/@l7mp/l7mp
$ node l7mp-proxy.js -c config.yaml -s
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module './monitoring'
[...]
```

Checking the content of the folder shows that monitoring.js is indeed missing. 
```sh
$ ls
LICENSE.md  README.md  cluster.js  config  error.js  l7mp-openapi.js  l7mp-proxy.js  l7mp.js  license.js  
listener.js  openapi  package.json  route.js  rule.js  session.js  stream-counter.js  stream.js
```

Copying [monitoring.js](https://github.com/l7mp/l7mp/raw/master/monitoring.js) from the repo makes l7mp work.

**Comment by rg0now** [comment]
Thanks a lot. Indeed, there was an error in the build pipeline. Can you please try whether v0.5.7 fixes this? https://www.npmjs.com/package/@l7mp/l7mp

**Comment by levaitamas** [comment]
v0.5.7 works flawlessly. Thanks!

**Comment by rg0now** [comment]
Thanks for reporting this!
